/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <iostream>
#include <stdio.h>
#include <STM32F407xx.h>
#include "STM32F407xx_gpio.h"


int main(void)
{
	uint32_t _delayvalue=0;
    /* Loop forever */
	while(1){

		printf("Hello STM");
		for(_delayvalue=0;_delayvalue<1000;_delayvalue++);
	}

		//for(;;);
}
